// This file contains all to the tailwind colors, and swatches.
// The values here were converted from their original `oklch` color-space to the widest-possible colorspace that Flutter currently supports, which is `display-p3`.
// The original values are taken from the Tailwind CSS source.

// Generated by `helpers/bin/parse_css_hex.dart`.

import 'dart:ui';
import 'package:flutter/material.dart';

/// All of the color swatches defined as a part of Tailwind.
///
/// Best used in material apps or other cases where a [MaterialColor] may be needed.
abstract class TwMaterialColors {
  /// Corresponds to `--color-red-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(97.1% 0.013 17.38deg)`
  ///
  /// `100`: `oklch(93.6% 0.032 17.717deg)`
  ///
  /// `200`: `oklch(88.5% 0.062 18.334deg)`
  ///
  /// `300`: `oklch(80.8% 0.114 19.571deg)`
  ///
  /// `400`: `oklch(70.4% 0.191 22.216deg)`
  ///
  /// `500`: `oklch(63.7% 0.237 25.331deg)`
  ///
  /// `600`: `oklch(57.7% 0.245 27.325deg)`
  ///
  /// `700`: `oklch(50.5% 0.213 27.518deg)`
  ///
  /// `800`: `oklch(44.4% 0.177 26.899deg)`
  ///
  /// `900`: `oklch(39.6% 0.141 25.723deg)`
  ///
  /// `950`: `oklch(25.8% 0.092 26.042deg)`
  static const MaterialColor red = MaterialColor(0xffef4444, {
    50: Color.from(
      alpha: 1.0,
      red: 0.9968413298978064,
      green: 0.9495853877602686,
      blue: 0.9495856277055247,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.9993008556247035,
      green: 0.8856429639115518,
      blue: 0.885676919384669,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 1.0,
      green: 0.7898433960204845,
      blue: 0.7900282556815345,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 1.0,
      green: 0.6346797909437316,
      blue: 0.6363713790456831,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 1.0,
      green: 0.39115272225547,
      blue: 0.40385679874567487,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.9826614269144941,
      green: 0.17179709064943344,
      blue: 0.213070203881435,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.9064575618212117,
      green: 0.0,
      blue: 0.04221458098674242,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.7568846979179918,
      green: 0.0,
      blue: 0.02875434793845987,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.6222081589386343,
      green: 0.028790581777508914,
      blue: 0.06893808765215198,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.5091704998481187,
      green: 0.09232881280396557,
      blue: 0.10068694419374077,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.2753966630524284,
      green: 0.031593156801625756,
      blue: 0.03449761438777331,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-orange-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98% 0.016 73.684deg)`
  ///
  /// `100`: `oklch(95.4% 0.038 75.164deg)`
  ///
  /// `200`: `oklch(90.1% 0.076 70.697deg)`
  ///
  /// `300`: `oklch(83.7% 0.128 66.29deg)`
  ///
  /// `400`: `oklch(75% 0.183 55.934deg)`
  ///
  /// `500`: `oklch(70.5% 0.213 47.604deg)`
  ///
  /// `600`: `oklch(64.6% 0.222 41.116deg)`
  ///
  /// `700`: `oklch(55.3% 0.195 38.402deg)`
  ///
  /// `800`: `oklch(47% 0.157 37.304deg)`
  ///
  /// `900`: `oklch(40.8% 0.123 38.172deg)`
  ///
  /// `950`: `oklch(26.6% 0.079 36.259deg)`
  static const MaterialColor orange = MaterialColor(0xfff97316, {
    50: Color.from(
      alpha: 1.0,
      red: 1.0,
      green: 0.9690530609479139,
      blue: 0.9292629025446291,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 1.0,
      green: 0.9288763358893751,
      blue: 0.8325848199111553,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 1.0,
      green: 0.8411152207277246,
      blue: 0.6568333437153624,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 1.0,
      green: 0.7222756429289523,
      blue: 0.41392701914925495,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 1.0,
      green: 0.5370230872254182,
      blue: 0.013840866896886444,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 1.0,
      green: 0.4107343102167065,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.9607054869223078,
      green: 0.2881907436987752,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.7918817553099516,
      green: 0.20726991176564247,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.6244982060754214,
      green: 0.17663322927910136,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.49511850192186896,
      green: 0.1654188885704691,
      blue: 0.04565223781437481,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.2664343583941732,
      green: 0.07441099241690186,
      blue: 0.021905324058652056,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-amber-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.7% 0.022 95.277deg)`
  ///
  /// `100`: `oklch(96.2% 0.059 95.617deg)`
  ///
  /// `200`: `oklch(92.4% 0.12 95.746deg)`
  ///
  /// `300`: `oklch(87.9% 0.169 91.605deg)`
  ///
  /// `400`: `oklch(82.8% 0.189 84.429deg)`
  ///
  /// `500`: `oklch(76.9% 0.188 70.08deg)`
  ///
  /// `600`: `oklch(66.6% 0.179 58.318deg)`
  ///
  /// `700`: `oklch(55.5% 0.163 48.998deg)`
  ///
  /// `800`: `oklch(47.3% 0.137 46.201deg)`
  ///
  /// `900`: `oklch(41.4% 0.112 45.904deg)`
  ///
  /// `950`: `oklch(27.9% 0.077 45.635deg)`
  static const MaterialColor amber = MaterialColor(0xfff59e0b, {
    50: Color.from(
      alpha: 1.0,
      red: 1.0,
      green: 0.9845063796507468,
      blue: 0.9199939131184264,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.9969999650348306,
      green: 0.9530826144695749,
      blue: 0.7775238957674817,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.9957299225875368,
      green: 0.9012048259607058,
      blue: 0.5221890750159695,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 1.0,
      green: 0.8238498632655084,
      blue: 0.18760540365348025,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.9997980962383602,
      green: 0.7274624507038914,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.9919608271544159,
      green: 0.6034274835044063,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.8837689331652921,
      green: 0.44335090165246266,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.7317888091953348,
      green: 0.3010233095055021,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.5903065497861455,
      green: 0.2337567370649532,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.48044631238858976,
      green: 0.19976529379362074,
      blue: 0.024833088801495658,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.2740671450150986,
      green: 0.09849269446586528,
      blue: 0.0046668129232549545,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-yellow-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.7% 0.026 102.212deg)`
  ///
  /// `100`: `oklch(97.3% 0.071 103.193deg)`
  ///
  /// `200`: `oklch(94.5% 0.129 101.54deg)`
  ///
  /// `300`: `oklch(90.5% 0.182 98.111deg)`
  ///
  /// `400`: `oklch(85.2% 0.199 91.936deg)`
  ///
  /// `500`: `oklch(79.5% 0.184 86.047deg)`
  ///
  /// `600`: `oklch(68.1% 0.162 75.834deg)`
  ///
  /// `700`: `oklch(55.4% 0.135 66.442deg)`
  ///
  /// `800`: `oklch(47.6% 0.114 61.907deg)`
  ///
  /// `900`: `oklch(42.1% 0.095 57.708deg)`
  ///
  /// `950`: `oklch(28.6% 0.066 53.813deg)`
  static const MaterialColor yellow = MaterialColor(0xffeab308, {
    50: Color.from(
      alpha: 1.0,
      red: 0.9955703006497284,
      green: 0.9878028178809947,
      blue: 0.9100785396857242,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.9969827660418394,
      green: 0.9767837338419195,
      blue: 0.7597211457153242,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.9986842056255189,
      green: 0.9411307327745028,
      blue: 0.5228279208112321,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 1.0,
      green: 0.8762567001636208,
      blue: 0.12571207403734358,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.9874546777774297,
      green: 0.7836666443083161,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.9385253740574679,
      green: 0.6939836310548068,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.8175540976089507,
      green: 0.5296359893141331,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.6510636052795632,
      green: 0.37320938235822104,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.5359094292771418,
      green: 0.2927126803751456,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.45048616210055165,
      green: 0.24240234180802323,
      blue: 0.04090362919975183,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.26186099193431506,
      green: 0.12400030228151696,
      blue: 0.01742056884840485,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-lime-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.6% 0.031 120.757deg)`
  ///
  /// `100`: `oklch(96.7% 0.067 122.328deg)`
  ///
  /// `200`: `oklch(93.8% 0.127 124.321deg)`
  ///
  /// `300`: `oklch(89.7% 0.196 126.665deg)`
  ///
  /// `400`: `oklch(84.1% 0.238 128.85deg)`
  ///
  /// `500`: `oklch(76.8% 0.233 130.85deg)`
  ///
  /// `600`: `oklch(64.8% 0.2 131.684deg)`
  ///
  /// `700`: `oklch(53.2% 0.157 131.589deg)`
  ///
  /// `800`: `oklch(45.3% 0.124 130.933deg)`
  ///
  /// `900`: `oklch(40.5% 0.101 131.063deg)`
  ///
  /// `950`: `oklch(27.4% 0.072 132.109deg)`
  static const MaterialColor lime = MaterialColor(0xff84cc16, {
    50: Color.from(
      alpha: 1.0,
      red: 0.9690420861599011,
      green: 0.9965202428182657,
      blue: 0.9062309790820153,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.9250763485679737,
      green: 0.9888006862836481,
      blue: 0.7933730437188472,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.8477643842504679,
      green: 0.9783046505481195,
      blue: 0.5999008411702398,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 0.7329368316134304,
      green: 0.9551594791962007,
      blue: 0.31780400890295274,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.6024434361607487,
      green: 0.9016712268885547,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.48729331258702974,
      green: 0.8099173831908861,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.36872012451731334,
      green: 0.6474890846414009,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.28480823426611096,
      green: 0.4915021238602884,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.2372255614222028,
      green: 0.3880722219410677,
      blue: 0.0,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.20701804907674248,
      green: 0.32722384306591396,
      blue: 0.05523693145217309,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.09908611119349481,
      green: 0.1812896114670005,
      blue: 0.010939874930351905,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-green-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.2% 0.018 155.826deg)`
  ///
  /// `100`: `oklch(96.2% 0.044 156.743deg)`
  ///
  /// `200`: `oklch(92.5% 0.084 155.995deg)`
  ///
  /// `300`: `oklch(87.1% 0.15 154.449deg)`
  ///
  /// `400`: `oklch(79.2% 0.209 151.711deg)`
  ///
  /// `500`: `oklch(72.3% 0.219 149.579deg)`
  ///
  /// `600`: `oklch(62.7% 0.194 149.214deg)`
  ///
  /// `700`: `oklch(52.7% 0.154 150.069deg)`
  ///
  /// `800`: `oklch(44.8% 0.119 151.328deg)`
  ///
  /// `900`: `oklch(39.3% 0.095 152.535deg)`
  ///
  /// `950`: `oklch(26.6% 0.065 152.934deg)`
  static const MaterialColor green = MaterialColor(0xff22c55e, {
    50: Color.from(
      alpha: 1.0,
      red: 0.9413932496954881,
      green: 0.9922020483060622,
      blue: 0.9570246264083583,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.8608796473786287,
      green: 0.9882110519823467,
      blue: 0.9046970580517256,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.7250790718564976,
      green: 0.9712606795730018,
      blue: 0.8118364375894778,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 0.4814550700410664,
      green: 0.9463488933134762,
      blue: 0.6570021981837473,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.019870585447826734,
      green: 0.8753122756349441,
      blue: 0.4485096789673145,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.7871556117517593,
      blue: 0.3156217584004383,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.651302259433401,
      blue: 0.24199256158359772,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.5099976610911293,
      blue: 0.2098096073112103,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.005796004781307278,
      green: 0.40147662633632414,
      blue: 0.1885884071779461,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.051125419243574034,
      green: 0.32868879391982897,
      blue: 0.17017246918161313,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.011995729439708063,
      green: 0.18100152929455007,
      blue: 0.08350354091228857,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-emerald-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(97.9% 0.021 166.113deg)`
  ///
  /// `100`: `oklch(95% 0.052 163.051deg)`
  ///
  /// `200`: `oklch(90.5% 0.093 164.15deg)`
  ///
  /// `300`: `oklch(84.5% 0.143 164.978deg)`
  ///
  /// `400`: `oklch(76.5% 0.177 163.223deg)`
  ///
  /// `500`: `oklch(69.6% 0.17 162.48deg)`
  ///
  /// `600`: `oklch(59.6% 0.145 163.225deg)`
  ///
  /// `700`: `oklch(50.8% 0.118 165.612deg)`
  ///
  /// `800`: `oklch(43.2% 0.095 166.913deg)`
  ///
  /// `900`: `oklch(37.8% 0.077 168.94deg)`
  ///
  /// `950`: `oklch(26.2% 0.051 172.552deg)`
  static const MaterialColor emerald = MaterialColor(0xff10b981, {
    50: Color.from(
      alpha: 1.0,
      red: 0.9243212973797708,
      green: 0.9920315603966104,
      blue: 0.9601800285455676,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.8159214762816597,
      green: 0.9808685466914197,
      blue: 0.8965166062525962,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.6444914835461703,
      green: 0.9558121939380889,
      blue: 0.8133241244185564,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 0.3698525275737171,
      green: 0.9150905511132272,
      blue: 0.7087672821381559,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.832592146722701,
      blue: 0.5723413430991994,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.7387891415713294,
      blue: 0.48928084904728614,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.5989388696851461,
      blue: 0.39898363827729094,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.47821954923258064,
      blue: 0.3335466773641863,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.3777278653241992,
      blue: 0.27057657519791706,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.30810386596750955,
      blue: 0.2298271317881626,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.17364809833424832,
      blue: 0.13278397501096117,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-teal-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.4% 0.014 180.72deg)`
  ///
  /// `100`: `oklch(95.3% 0.051 180.801deg)`
  ///
  /// `200`: `oklch(91% 0.096 180.426deg)`
  ///
  /// `300`: `oklch(85.5% 0.138 181.071deg)`
  ///
  /// `400`: `oklch(77.7% 0.152 181.912deg)`
  ///
  /// `500`: `oklch(70.4% 0.14 182.503deg)`
  ///
  /// `600`: `oklch(60% 0.118 184.704deg)`
  ///
  /// `700`: `oklch(51.1% 0.096 186.391deg)`
  ///
  /// `800`: `oklch(43.7% 0.078 188.216deg)`
  ///
  /// `900`: `oklch(38.6% 0.063 188.416deg)`
  ///
  /// `950`: `oklch(27.7% 0.046 192.524deg)`
  static const MaterialColor teal = MaterialColor(0xff14b8a6, {
    50: Color.from(
      alpha: 1.0,
      red: 0.9422644158358698,
      green: 0.9925186060972936,
      blue: 0.9809167536907614,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.7967792248302408,
      green: 0.9858463319166267,
      blue: 0.9457265007541654,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.5870300825650485,
      green: 0.9674542323535963,
      blue: 0.8945855391080414,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 0.27562052605978205,
      green: 0.9274332046179096,
      blue: 0.8335047024203682,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.8352503934977442,
      blue: 0.7433175862514432,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.7333587456917721,
      blue: 0.6548707925920922,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.5892682376396243,
      blue: 0.5372884597753127,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.4689987755513932,
      blue: 0.43497160787600536,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.3731432796461609,
      blue: 0.3521346605413762,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.04200313629213683,
      green: 0.3081708295721075,
      blue: 0.29175599091547855,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.00812145296534945,
      green: 0.1847563837693368,
      blue: 0.1808228176700744,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-cyan-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.4% 0.019 200.873deg)`
  ///
  /// `100`: `oklch(95.6% 0.045 203.388deg)`
  ///
  /// `200`: `oklch(91.7% 0.08 205.041deg)`
  ///
  /// `300`: `oklch(86.5% 0.127 207.078deg)`
  ///
  /// `400`: `oklch(78.9% 0.154 211.53deg)`
  ///
  /// `500`: `oklch(71.5% 0.143 215.221deg)`
  ///
  /// `600`: `oklch(60.9% 0.126 221.723deg)`
  ///
  /// `700`: `oklch(52% 0.105 223.128deg)`
  ///
  /// `800`: `oklch(45% 0.085 224.283deg)`
  ///
  /// `900`: `oklch(39.8% 0.07 227.392deg)`
  ///
  /// `950`: `oklch(30.2% 0.056 229.695deg)`
  static const MaterialColor cyan = MaterialColor(0xff06b6d4, {
    50: Color.from(
      alpha: 1.0,
      red: 0.9250037783949456,
      green: 0.9960225097892738,
      blue: 0.9999691378169085,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.809272255488591,
      green: 0.9805906061430231,
      blue: 0.9965360545897718,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.6366476289542482,
      green: 0.9554242812125199,
      blue: 0.992155275858006,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 0.32666679492104844,
      green: 0.9169947276382833,
      blue: 0.9913581535132162,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.8273619091589361,
      blue: 0.9509645825453114,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.7218724374054263,
      blue: 0.8573380164511498,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.5741973106149573,
      blue: 0.7225723514690859,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.4590370456425879,
      blue: 0.5832521237778526,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.3711744099307161,
      blue: 0.4712478634198077,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.06372827055484484,
      green: 0.3067085829441845,
      blue: 0.39374164793423666,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.021187917882951292,
      green: 0.2006470972520607,
      blue: 0.26983208162944683,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-sky-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(97.7% 0.013 236.62deg)`
  ///
  /// `100`: `oklch(95.1% 0.026 236.824deg)`
  ///
  /// `200`: `oklch(90.1% 0.058 230.902deg)`
  ///
  /// `300`: `oklch(82.8% 0.111 230.318deg)`
  ///
  /// `400`: `oklch(74.6% 0.16 232.661deg)`
  ///
  /// `500`: `oklch(68.5% 0.169 237.323deg)`
  ///
  /// `600`: `oklch(58.8% 0.158 241.966deg)`
  ///
  /// `700`: `oklch(50% 0.134 242.749deg)`
  ///
  /// `800`: `oklch(44.3% 0.11 240.79deg)`
  ///
  /// `900`: `oklch(39.1% 0.09 240.876deg)`
  ///
  /// `950`: `oklch(29.3% 0.066 243.157deg)`
  static const MaterialColor sky = MaterialColor(0xff0ea5e9, {
    50: Color.from(
      alpha: 1.0,
      red: 0.939836694237885,
      green: 0.9765926487525279,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.8755857141045688,
      green: 0.9489379805311825,
      blue: 0.9978108000784495,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.7218523376019134,
      green: 0.9026974816558876,
      blue: 0.9970122035841437,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 0.45321832304666637,
      green: 0.8316647919920261,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.7364118766007559,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.6497637788539826,
      blue: 0.957131088036632,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.5181664436816554,
      blue: 0.819799643258263,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.4116348731184033,
      blue: 0.6602958698381596,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.0,
      green: 0.3490170071775053,
      blue: 0.5398579214891074,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.006753342546324195,
      green: 0.2902710902372397,
      blue: 0.4411054289229597,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.019814980475584585,
      green: 0.18393749827221328,
      blue: 0.2905612313931386,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-blue-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(97% 0.014 254.604deg)`
  ///
  /// `100`: `oklch(93.2% 0.032 255.585deg)`
  ///
  /// `200`: `oklch(88.2% 0.059 254.128deg)`
  ///
  /// `300`: `oklch(80.9% 0.105 251.813deg)`
  ///
  /// `400`: `oklch(70.7% 0.165 254.624deg)`
  ///
  /// `500`: `oklch(62.3% 0.214 259.815deg)`
  ///
  /// `600`: `oklch(54.6% 0.245 262.881deg)`
  ///
  /// `700`: `oklch(48.8% 0.243 264.376deg)`
  ///
  /// `800`: `oklch(42.4% 0.199 265.638deg)`
  ///
  /// `900`: `oklch(37.9% 0.146 265.522deg)`
  ///
  /// `950`: `oklch(28.2% 0.091 267.935deg)`
  static const MaterialColor blue = MaterialColor(0xff3b82f6, {
    50: Color.from(
      alpha: 1.0,
      red: 0.9369397781483667,
      green: 0.9640346236130352,
      blue: 0.998871849450793,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.8582405392342604,
      green: 0.9178275221599572,
      blue: 0.997270487413772,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.7450929940300554,
      green: 0.8586637667571715,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 0.5565924009906972,
      green: 0.7731643436401513,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.3157993465908606,
      green: 0.6355904471566127,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.16933250478016887,
      green: 0.4980494693037492,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.0836190689884039,
      green: 0.3644171340711107,
      blue: 0.9863430390798343,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.07790771362644017,
      green: 0.27913518695168466,
      blue: 0.901774415938853,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.09978120745081645,
      green: 0.23377008556238332,
      blue: 0.7229223923602304,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.10905590964395853,
      green: 0.22219257404237064,
      blue: 0.5575136150170836,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.08726257662821399,
      green: 0.14313230082127698,
      blue: 0.3356920422858533,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-indigo-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(96.2% 0.018 272.314deg)`
  ///
  /// `100`: `oklch(93% 0.034 272.788deg)`
  ///
  /// `200`: `oklch(87% 0.065 274.039deg)`
  ///
  /// `300`: `oklch(78.5% 0.115 274.713deg)`
  ///
  /// `400`: `oklch(67.3% 0.182 276.935deg)`
  ///
  /// `500`: `oklch(58.5% 0.233 277.117deg)`
  ///
  /// `600`: `oklch(51.1% 0.262 276.966deg)`
  ///
  /// `700`: `oklch(45.7% 0.24 277.023deg)`
  ///
  /// `800`: `oklch(39.8% 0.195 277.366deg)`
  ///
  /// `900`: `oklch(35.9% 0.144 278.697deg)`
  ///
  /// `950`: `oklch(25.7% 0.09 281.288deg)`
  static const MaterialColor indigo = MaterialColor(0xff6366f1, {
    50: Color.from(
      alpha: 1.0,
      red: 0.9333945401373415,
      green: 0.9491385901836252,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.8779962734221028,
      green: 0.9058982464712464,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.7783517053947335,
      green: 0.8231921402624682,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 0.6391280283624043,
      green: 0.7021304925672912,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.4878469518853686,
      green: 0.5265172946061927,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.38217605101248664,
      green: 0.3718883055748194,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.31088547370970593,
      green: 0.2244045112578637,
      blue: 0.9662612237308176,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.26435297185196566,
      green: 0.1765924729124599,
      blue: 0.8448341023580314,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.21542690950389148,
      green: 0.16322345397783938,
      blue: 0.6737073985661062,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.19164835902250105,
      green: 0.172645159589724,
      blue: 0.5226693832212137,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.117133840675263,
      green: 0.10263016972631478,
      blue: 0.3006191274903975,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-violet-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(96.9% 0.016 293.756deg)`
  ///
  /// `100`: `oklch(94.3% 0.029 294.588deg)`
  ///
  /// `200`: `oklch(89.4% 0.057 293.283deg)`
  ///
  /// `300`: `oklch(81.1% 0.111 293.571deg)`
  ///
  /// `400`: `oklch(70.2% 0.183 293.541deg)`
  ///
  /// `500`: `oklch(60.6% 0.25 292.717deg)`
  ///
  /// `600`: `oklch(54.1% 0.281 293.009deg)`
  ///
  /// `700`: `oklch(49.1% 0.27 292.581deg)`
  ///
  /// `800`: `oklch(43.2% 0.232 292.759deg)`
  ///
  /// `900`: `oklch(38% 0.189 293.745deg)`
  ///
  /// `950`: `oklch(28.3% 0.141 291.089deg)`
  static const MaterialColor violet = MaterialColor(0xff8b5cf6, {
    50: Color.from(
      alpha: 1.0,
      red: 0.9605924924324128,
      green: 0.9527792887293457,
      blue: 0.9996634988527536,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.9290421500860022,
      green: 0.9130081548129565,
      blue: 0.9970683801883752,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.8665415265005071,
      green: 0.8378734748372842,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 0.7700671196457545,
      green: 0.7039359698697322,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.6526055482928625,
      green: 0.5169347069554401,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.5559262801505187,
      green: 0.3181637760329294,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.4999111411140554,
      green: 0.133704759774065,
      blue: 0.9959982436016886,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.43968586642094437,
      green: 0.03142319427593838,
      blue: 0.9064205865926495,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.36538352700094195,
      green: 0.05553910583586872,
      blue: 0.7533062777024284,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.30247334338543236,
      green: 0.08911598173638319,
      blue: 0.603715712008197,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.1825469302367186,
      green: 0.05090218177257499,
      blue: 0.40635261802999106,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-purple-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(97.7% 0.014 308.299deg)`
  ///
  /// `100`: `oklch(94.6% 0.033 307.174deg)`
  ///
  /// `200`: `oklch(90.2% 0.063 306.703deg)`
  ///
  /// `300`: `oklch(82.7% 0.119 306.383deg)`
  ///
  /// `400`: `oklch(71.4% 0.203 305.504deg)`
  ///
  /// `500`: `oklch(62.7% 0.265 303.9deg)`
  ///
  /// `600`: `oklch(55.8% 0.288 302.321deg)`
  ///
  /// `700`: `oklch(49.6% 0.265 301.924deg)`
  ///
  /// `800`: `oklch(43.8% 0.218 303.724deg)`
  ///
  /// `900`: `oklch(38.1% 0.176 304.987deg)`
  ///
  /// `950`: `oklch(29.1% 0.149 302.717deg)`
  static const MaterialColor purple = MaterialColor(0xffa855f7, {
    50: Color.from(
      alpha: 1.0,
      red: 0.9804396820431579,
      green: 0.9611090499837506,
      blue: 0.9997745770307146,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.9525600810438358,
      green: 0.9090818994277462,
      blue: 0.999977341397205,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.9150137092144975,
      green: 0.8330873956775616,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 0.8544051973391201,
      green: 0.6977941786303382,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.7595676616298562,
      green: 0.4798001127722575,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.6779096243481626,
      green: 0.27594198238283846,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.5968394190437776,
      green: 0.06172951297677844,
      blue: 0.9813577660607263,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.5099056905764929,
      green: 0.0,
      blue: 0.8572576419488928,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.4299933486431484,
      green: 0.06663919706169008,
      blue: 0.6907452186509343,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.3507220152600924,
      green: 0.08730051114975496,
      blue: 0.5451927861997657,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.23463118943800837,
      green: 0.01178013535032706,
      blue: 0.40136923732375596,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-fuchsia-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(97.7% 0.017 320.058deg)`
  ///
  /// `100`: `oklch(95.2% 0.037 318.852deg)`
  ///
  /// `200`: `oklch(90.3% 0.076 319.62deg)`
  ///
  /// `300`: `oklch(83.3% 0.145 321.434deg)`
  ///
  /// `400`: `oklch(74% 0.238 322.16deg)`
  ///
  /// `500`: `oklch(66.7% 0.295 322.15deg)`
  ///
  /// `600`: `oklch(59.1% 0.293 322.896deg)`
  ///
  /// `700`: `oklch(51.8% 0.253 323.949deg)`
  ///
  /// `800`: `oklch(45.2% 0.211 324.591deg)`
  ///
  /// `900`: `oklch(40.1% 0.17 325.612deg)`
  ///
  /// `950`: `oklch(29.3% 0.136 325.661deg)`
  static const MaterialColor fuchsia = MaterialColor(0xffd946ef, {
    50: Color.from(
      alpha: 1.0,
      red: 0.9914102302726974,
      green: 0.9567697454217757,
      blue: 0.9991073704900254,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.981551209546366,
      green: 0.9089312598723259,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.9639648436308,
      green: 0.8133429781917612,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 0.9550995681947064,
      green: 0.6572811098996214,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.9299384509491767,
      green: 0.41756641494187297,
      blue: 1.0,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.8836880256353928,
      green: 0.16574675262196384,
      blue: 0.984501375485079,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.7836063046344383,
      green: 0.0,
      blue: 0.871541063451013,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.6584703175652419,
      green: 0.0,
      blue: 0.7179514130186864,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.5413972763623807,
      green: 0.0051706855634201,
      blue: 0.5817819047303414,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.4479151926730907,
      green: 0.07534362967602687,
      blue: 0.4695966711274993,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.2938792664851057,
      green: 0.0014664182159384923,
      blue: 0.31061853896507824,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-pink-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(97.1% 0.014 343.198deg)`
  ///
  /// `100`: `oklch(94.8% 0.028 342.258deg)`
  ///
  /// `200`: `oklch(89.9% 0.061 343.231deg)`
  ///
  /// `300`: `oklch(82.3% 0.12 346.018deg)`
  ///
  /// `400`: `oklch(71.8% 0.202 349.761deg)`
  ///
  /// `500`: `oklch(65.6% 0.241 354.308deg)`
  ///
  /// `600`: `oklch(59.2% 0.249 0.584deg)`
  ///
  /// `700`: `oklch(52.5% 0.223 3.958deg)`
  ///
  /// `800`: `oklch(45.9% 0.187 3.815deg)`
  ///
  /// `900`: `oklch(40.8% 0.153 2.432deg)`
  ///
  /// `950`: `oklch(28.4% 0.109 3.907deg)`
  static const MaterialColor pink = MaterialColor(0xffec4899, {
    50: Color.from(
      alpha: 1.0,
      red: 0.9913174727041209,
      green: 0.9486181428707446,
      blue: 0.9719057954178864,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.9886688330320629,
      green: 0.9052759852275493,
      blue: 0.9529445710701073,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.9876744334901156,
      green: 0.809049321010355,
      blue: 0.9107282689168849,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 0.9940834148614138,
      green: 0.6464798699967504,
      blue: 0.8371420996348686,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.9856091011423914,
      green: 0.39204093654502054,
      blue: 0.7138619736617519,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.9658054466913671,
      green: 0.198138824436301,
      blue: 0.6043243492073168,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.9013361381595539,
      green: 0.0,
      blue: 0.463410047501508,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.7777568218580173,
      green: 0.0,
      blue: 0.3589229194060831,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.6386031540919963,
      green: 0.0,
      blue: 0.29804380788184237,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.5251818453849647,
      green: 0.06328236908134222,
      blue: 0.26133394569178936,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.3180017367733104,
      green: 0.015083709086403024,
      blue: 0.13981923147075617,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-rose-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(96.9% 0.015 12.422deg)`
  ///
  /// `100`: `oklch(94.1% 0.03 12.58deg)`
  ///
  /// `200`: `oklch(89.2% 0.058 10.001deg)`
  ///
  /// `300`: `oklch(81% 0.117 11.638deg)`
  ///
  /// `400`: `oklch(71.2% 0.194 13.428deg)`
  ///
  /// `500`: `oklch(64.5% 0.246 16.439deg)`
  ///
  /// `600`: `oklch(58.6% 0.253 17.585deg)`
  ///
  /// `700`: `oklch(51.4% 0.222 16.935deg)`
  ///
  /// `800`: `oklch(45.5% 0.188 13.697deg)`
  ///
  /// `900`: `oklch(41% 0.159 10.272deg)`
  ///
  /// `950`: `oklch(27.1% 0.105 12.094deg)`
  static const MaterialColor rose = MaterialColor(0xfff43f5e, {
    50: Color.from(
      alpha: 1.0,
      red: 0.999023129022007,
      green: 0.9447283627727603,
      blue: 0.9486036054863457,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 1.0,
      green: 0.8934201647145283,
      blue: 0.9013286284309072,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 1.0,
      green: 0.80110757550013,
      blue: 0.8256557269990478,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 1.0,
      green: 0.6299288099762534,
      blue: 0.6795160126296866,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 1.0,
      green: 0.38886055095167105,
      blue: 0.49433155578340476,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 1.0,
      green: 0.12461523096854374,
      blue: 0.33900326408201836,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.9273908931331772,
      green: 0.0,
      blue: 0.24870920184022394,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.778506380663911,
      green: 0.0,
      blue: 0.2106962828258086,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.6466910159034669,
      green: 0.0,
      blue: 0.2116679322685096,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.5445029066403653,
      green: 0.030038689514920575,
      blue: 0.21069892975641963,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.30314696440839567,
      green: 0.008819827171387089,
      blue: 0.09585870908751976,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-slate-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.4% 0.003 247.858deg)`
  ///
  /// `100`: `oklch(96.8% 0.007 247.896deg)`
  ///
  /// `200`: `oklch(92.9% 0.013 255.508deg)`
  ///
  /// `300`: `oklch(86.9% 0.022 252.894deg)`
  ///
  /// `400`: `oklch(70.4% 0.04 256.788deg)`
  ///
  /// `500`: `oklch(55.4% 0.046 257.417deg)`
  ///
  /// `600`: `oklch(44.6% 0.043 257.281deg)`
  ///
  /// `700`: `oklch(37.2% 0.044 257.287deg)`
  ///
  /// `800`: `oklch(27.9% 0.041 260.031deg)`
  ///
  /// `900`: `oklch(20.8% 0.042 265.755deg)`
  ///
  /// `950`: `oklch(12.9% 0.042 264.695deg)`
  static const MaterialColor slate = MaterialColor(0xff64748b, {
    50: Color.from(
      alpha: 1.0,
      red: 0.9731488522540469,
      green: 0.9800426054662702,
      blue: 0.9869375219463618,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.9444747089424728,
      green: 0.9604953704340579,
      blue: 0.9765152883989355,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.8859544002236996,
      green: 0.9101960351218827,
      blue: 0.9425160502172096,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 0.7923478768572394,
      green: 0.8358279496588396,
      blue: 0.887972421651476,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.5648487363231489,
      green: 0.6316962763094215,
      blue: 0.7252391411445487,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.38391206804084616,
      green: 0.45478722134869126,
      blue: 0.5566604979380744,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.2709961605080002,
      green: 0.3340815485807492,
      blue: 0.4241887696423897,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.19350013489640774,
      green: 0.2552660391485496,
      blue: 0.34348723421124183,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.1121277103056045,
      green: 0.16004398467081402,
      blue: 0.23867248940669916,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.05718432354423799,
      green: 0.09004246505833119,
      blue: 0.16879599591942343,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.0074293207417662965,
      green: 0.023281749419033573,
      blue: 0.09250507951914497,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-gray-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.5% 0.002 247.839deg)`
  ///
  /// `100`: `oklch(96.7% 0.003 264.542deg)`
  ///
  /// `200`: `oklch(92.8% 0.006 264.531deg)`
  ///
  /// `300`: `oklch(87.2% 0.01 258.338deg)`
  ///
  /// `400`: `oklch(70.7% 0.022 261.325deg)`
  ///
  /// `500`: `oklch(55.1% 0.027 264.364deg)`
  ///
  /// `600`: `oklch(44.6% 0.03 256.802deg)`
  ///
  /// `700`: `oklch(37.3% 0.034 259.733deg)`
  ///
  /// `800`: `oklch(27.8% 0.033 256.848deg)`
  ///
  /// `900`: `oklch(21% 0.034 264.665deg)`
  ///
  /// `950`: `oklch(13% 0.028 261.692deg)`
  static const MaterialColor gray = MaterialColor(0xff6b7280, {
    50: Color.from(
      alpha: 1.0,
      red: 0.9763942292220046,
      green: 0.980992170198118,
      blue: 0.985589520180738,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.9528385020410971,
      green: 0.9569317557631168,
      blue: 0.9651184315219946,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.8983431377629695,
      green: 0.9064381730859447,
      blue: 0.9226285306518572,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 0.8190176740578249,
      green: 0.835814874191183,
      blue: 0.8610087609476719,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.600008809293853,
      green: 0.631395176614166,
      blue: 0.6852225804848499,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.4154543457320376,
      green: 0.4470909709995556,
      blue: 0.5104967709257803,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.2888334530513595,
      green: 0.33354592473227984,
      blue: 0.39611636404285216,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.21153233111089925,
      green: 0.25502958900962136,
      blue: 0.3247052203348353,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.11697349561786843,
      green: 0.16075427591841235,
      blue: 0.22201550047909063,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.06452562744067614,
      green: 0.09374159032906379,
      blue: 0.1567844222805852,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.011584726817166158,
      green: 0.027607331822166813,
      blue: 0.07187579196071325,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-zinc-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.5% 0 0deg)`
  ///
  /// `100`: `oklch(96.7% 0.001 286.375deg)`
  ///
  /// `200`: `oklch(92% 0.004 286.32deg)`
  ///
  /// `300`: `oklch(87.1% 0.006 286.286deg)`
  ///
  /// `400`: `oklch(70.5% 0.015 286.067deg)`
  ///
  /// `500`: `oklch(55.2% 0.016 285.938deg)`
  ///
  /// `600`: `oklch(44.2% 0.017 285.786deg)`
  ///
  /// `700`: `oklch(37% 0.013 285.805deg)`
  ///
  /// `800`: `oklch(27.4% 0.006 286.033deg)`
  ///
  /// `900`: `oklch(21% 0.006 285.885deg)`
  ///
  /// `950`: `oklch(14.1% 0.005 285.823deg)`
  static const MaterialColor zinc = MaterialColor(0xff71717a, {
    50: Color.from(
      alpha: 1.0,
      red: 0.9802559798510254,
      green: 0.9802559798510223,
      blue: 0.9802559798510234,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.9563849496780178,
      green: 0.956385327381709,
      blue: 0.9593429413177964,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.89447672191126,
      green: 0.8944769095405364,
      blue: 0.9061506216932224,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 0.8310875321463276,
      green: 0.8310831943235716,
      blue: 0.8483446141912064,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.6226133255430648,
      green: 0.6225615603365655,
      blue: 0.6633595925781614,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.442995204114309,
      green: 0.4429292163792982,
      blue: 0.4838042927551955,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.3211818615075131,
      green: 0.3210902018604896,
      blue: 0.3621075403712351,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.24648490356540992,
      green: 0.24644706732691124,
      blue: 0.2764649024503501,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.15289691637693334,
      green: 0.1528868480870119,
      blue: 0.16577024780700775,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.0937963911263835,
      green: 0.09379291703454015,
      blue: 0.10583165480724857,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.03537426084125087,
      green: 0.035358999667475584,
      blue: 0.04431813654457029,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-neutral-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.5% 0 0deg)`
  ///
  /// `100`: `oklch(97% 0 0deg)`
  ///
  /// `200`: `oklch(92.2% 0 0deg)`
  ///
  /// `300`: `oklch(87% 0 0deg)`
  ///
  /// `400`: `oklch(70.8% 0 0deg)`
  ///
  /// `500`: `oklch(55.6% 0 0deg)`
  ///
  /// `600`: `oklch(43.9% 0 0deg)`
  ///
  /// `700`: `oklch(37.1% 0 0deg)`
  ///
  /// `800`: `oklch(26.9% 0 0deg)`
  ///
  /// `900`: `oklch(20.5% 0 0deg)`
  ///
  /// `950`: `oklch(14.5% 0 0deg)`
  static const MaterialColor neutral = MaterialColor(0xff737373, {
    50: Color.from(
      alpha: 1.0,
      red: 0.9802559798510254,
      green: 0.9802559798510223,
      blue: 0.9802559798510234,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.9605869869200209,
      green: 0.9605869869200175,
      blue: 0.9605869869200186,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.898160663585647,
      green: 0.8981606635856437,
      blue: 0.8981606635856448,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 0.8314444503075229,
      green: 0.8314444503075196,
      blue: 0.8314444503075206,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.6301632042746157,
      green: 0.630163204274614,
      blue: 0.6301632042746145,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.4515192429625196,
      green: 0.45151924296251794,
      blue: 0.4515192429625184,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.3219928468994376,
      green: 0.32199284689943625,
      blue: 0.32199284689943664,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.2504709015424902,
      green: 0.2504709015424895,
      blue: 0.25047090154248974,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.14938207763559994,
      green: 0.14938207763559935,
      blue: 0.14938207763559946,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.09052740524946729,
      green: 0.09052740524946662,
      blue: 0.09052740524946687,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.03938823500000018,
      green: 0.0393882349999999,
      blue: 0.03938823499999997,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  /// Corresponds to `--color-stone-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.5% 0.001 106.423deg)`
  ///
  /// `100`: `oklch(97% 0.001 106.424deg)`
  ///
  /// `200`: `oklch(92.3% 0.003 48.717deg)`
  ///
  /// `300`: `oklch(86.9% 0.005 56.366deg)`
  ///
  /// `400`: `oklch(70.9% 0.01 56.259deg)`
  ///
  /// `500`: `oklch(55.3% 0.013 58.071deg)`
  ///
  /// `600`: `oklch(44.4% 0.011 73.639deg)`
  ///
  /// `700`: `oklch(37.4% 0.01 67.558deg)`
  ///
  /// `800`: `oklch(26.8% 0.007 34.298deg)`
  ///
  /// `900`: `oklch(21.6% 0.006 56.043deg)`
  ///
  /// `950`: `oklch(14.7% 0.004 49.25deg)`
  static const MaterialColor stone = MaterialColor(0xff78716c, {
    50: Color.from(
      alpha: 1.0,
      red: 0.9805331813597401,
      green: 0.9805335062292123,
      blue: 0.9775605364885184,
      colorSpace: ColorSpace.sRGB,
    ),
    100: Color.from(
      alpha: 1.0,
      red: 0.960863086166457,
      green: 0.9608634557226151,
      blue: 0.9579018561508262,
      colorSpace: ColorSpace.sRGB,
    ),
    200: Color.from(
      alpha: 1.0,
      red: 0.9067104284114366,
      green: 0.8975317470031251,
      blue: 0.8929412664587455,
      colorSpace: ColorSpace.sRGB,
    ),
    300: Color.from(
      alpha: 1.0,
      red: 0.841165816892227,
      green: 0.8275092269394133,
      blue: 0.8184011122745036,
      colorSpace: ColorSpace.sRGB,
    ),
    400: Color.from(
      alpha: 1.0,
      red: 0.6521305635454833,
      green: 0.626222726718384,
      blue: 0.6089382265532823,
      colorSpace: ColorSpace.sRGB,
    ),
    500: Color.from(
      alpha: 1.0,
      red: 0.47271417908751895,
      green: 0.4420021517775604,
      blue: 0.42003730060271827,
      colorSpace: ColorSpace.sRGB,
    ),
    600: Color.from(
      alpha: 1.0,
      red: 0.342650471461511,
      green: 0.32467542521934045,
      blue: 0.3021830556172036,
      colorSpace: ColorSpace.sRGB,
    ),
    700: Color.from(
      alpha: 1.0,
      red: 0.26848797345273423,
      green: 0.2504235021060842,
      blue: 0.2323311942980948,
      colorSpace: ColorSpace.sRGB,
    ),
    800: Color.from(
      alpha: 1.0,
      red: 0.16162397505748416,
      green: 0.144194791832033,
      blue: 0.13983765564387854,
      colorSpace: ColorSpace.sRGB,
    ),
    900: Color.from(
      alpha: 1.0,
      red: 0.10951207057580745,
      green: 0.09798768012353223,
      blue: 0.09030699498911524,
      colorSpace: ColorSpace.sRGB,
    ),
    950: Color.from(
      alpha: 1.0,
      red: 0.04695921239450542,
      green: 0.039356111711251765,
      blue: 0.035544484014150765,
      colorSpace: ColorSpace.sRGB,
    ),
  });

  static const Map<String, MaterialColor> colorList = {
    'red': red,
    'orange': orange,
    'amber': amber,
    'yellow': yellow,
    'lime': lime,
    'green': green,
    'emerald': emerald,
    'teal': teal,
    'cyan': cyan,
    'sky': sky,
    'blue': blue,
    'indigo': indigo,
    'violet': violet,
    'purple': purple,
    'fuchsia': fuchsia,
    'pink': pink,
    'rose': rose,
    'slate': slate,
    'gray': gray,
    'zinc': zinc,
    'neutral': neutral,
    'stone': stone,
  };
}
