// This file contains all to the tailwind color swatches, defined using their nearest hex values.
// These values are taken from the Tailwind CSS website.

// Generated by `helpers/bin/parse_css_hex.dart`.

import 'package:flutter/rendering.dart';

/// All of the color swatches defined as a part of Tailwind.
///
/// These are defined as hex values.
/// Best used in cases where you want to modify these colors further.
abstract class TwSwatchHexColors {
  /// Corresponds to `--color-red-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(97.1% 0.013 17.38deg)`
  ///
  /// `100`: `oklch(93.6% 0.032 17.717deg)`
  ///
  /// `200`: `oklch(88.5% 0.062 18.334deg)`
  ///
  /// `300`: `oklch(80.8% 0.114 19.571deg)`
  ///
  /// `400`: `oklch(70.4% 0.191 22.216deg)`
  ///
  /// `500`: `oklch(63.7% 0.237 25.331deg)`
  ///
  /// `600`: `oklch(57.7% 0.245 27.325deg)`
  ///
  /// `700`: `oklch(50.5% 0.213 27.518deg)`
  ///
  /// `800`: `oklch(44.4% 0.177 26.899deg)`
  ///
  /// `900`: `oklch(39.6% 0.141 25.723deg)`
  ///
  /// `950`: `oklch(25.8% 0.092 26.042deg)`
  static const ColorSwatch<int> red = ColorSwatch(0xffef4444, {
    50: Color(0xfffef2f2),
    100: Color(0xfffee2e2),
    200: Color(0xfffecaca),
    300: Color(0xfffca5a5),
    400: Color(0xfff87171),
    500: Color(0xffef4444),
    600: Color(0xffdc2626),
    700: Color(0xffb91c1c),
    800: Color(0xff991b1b),
    900: Color(0xff7f1d1d),
    950: Color(0xff450a0a),
  });

  /// Corresponds to `--color-orange-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98% 0.016 73.684deg)`
  ///
  /// `100`: `oklch(95.4% 0.038 75.164deg)`
  ///
  /// `200`: `oklch(90.1% 0.076 70.697deg)`
  ///
  /// `300`: `oklch(83.7% 0.128 66.29deg)`
  ///
  /// `400`: `oklch(75% 0.183 55.934deg)`
  ///
  /// `500`: `oklch(70.5% 0.213 47.604deg)`
  ///
  /// `600`: `oklch(64.6% 0.222 41.116deg)`
  ///
  /// `700`: `oklch(55.3% 0.195 38.402deg)`
  ///
  /// `800`: `oklch(47% 0.157 37.304deg)`
  ///
  /// `900`: `oklch(40.8% 0.123 38.172deg)`
  ///
  /// `950`: `oklch(26.6% 0.079 36.259deg)`
  static const ColorSwatch<int> orange = ColorSwatch(0xfff97316, {
    50: Color(0xfffff7ed),
    100: Color(0xffffedd5),
    200: Color(0xfffed7aa),
    300: Color(0xfffdba74),
    400: Color(0xfffb923c),
    500: Color(0xfff97316),
    600: Color(0xffea580c),
    700: Color(0xffc2410c),
    800: Color(0xff9a3412),
    900: Color(0xff7c2d12),
    950: Color(0xff431407),
  });

  /// Corresponds to `--color-amber-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.7% 0.022 95.277deg)`
  ///
  /// `100`: `oklch(96.2% 0.059 95.617deg)`
  ///
  /// `200`: `oklch(92.4% 0.12 95.746deg)`
  ///
  /// `300`: `oklch(87.9% 0.169 91.605deg)`
  ///
  /// `400`: `oklch(82.8% 0.189 84.429deg)`
  ///
  /// `500`: `oklch(76.9% 0.188 70.08deg)`
  ///
  /// `600`: `oklch(66.6% 0.179 58.318deg)`
  ///
  /// `700`: `oklch(55.5% 0.163 48.998deg)`
  ///
  /// `800`: `oklch(47.3% 0.137 46.201deg)`
  ///
  /// `900`: `oklch(41.4% 0.112 45.904deg)`
  ///
  /// `950`: `oklch(27.9% 0.077 45.635deg)`
  static const ColorSwatch<int> amber = ColorSwatch(0xfff59e0b, {
    50: Color(0xfffffbeb),
    100: Color(0xfffef3c7),
    200: Color(0xfffde68a),
    300: Color(0xfffcd34d),
    400: Color(0xfffbbf24),
    500: Color(0xfff59e0b),
    600: Color(0xffd97706),
    700: Color(0xffb45309),
    800: Color(0xff92400e),
    900: Color(0xff78350f),
    950: Color(0xff451a03),
  });

  /// Corresponds to `--color-yellow-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.7% 0.026 102.212deg)`
  ///
  /// `100`: `oklch(97.3% 0.071 103.193deg)`
  ///
  /// `200`: `oklch(94.5% 0.129 101.54deg)`
  ///
  /// `300`: `oklch(90.5% 0.182 98.111deg)`
  ///
  /// `400`: `oklch(85.2% 0.199 91.936deg)`
  ///
  /// `500`: `oklch(79.5% 0.184 86.047deg)`
  ///
  /// `600`: `oklch(68.1% 0.162 75.834deg)`
  ///
  /// `700`: `oklch(55.4% 0.135 66.442deg)`
  ///
  /// `800`: `oklch(47.6% 0.114 61.907deg)`
  ///
  /// `900`: `oklch(42.1% 0.095 57.708deg)`
  ///
  /// `950`: `oklch(28.6% 0.066 53.813deg)`
  static const ColorSwatch<int> yellow = ColorSwatch(0xffeab308, {
    50: Color(0xfffefce8),
    100: Color(0xfffef9c3),
    200: Color(0xfffef08a),
    300: Color(0xfffde047),
    400: Color(0xfffacc15),
    500: Color(0xffeab308),
    600: Color(0xffca8a04),
    700: Color(0xffa16207),
    800: Color(0xff854d0e),
    900: Color(0xff713f12),
    950: Color(0xff422006),
  });

  /// Corresponds to `--color-lime-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.6% 0.031 120.757deg)`
  ///
  /// `100`: `oklch(96.7% 0.067 122.328deg)`
  ///
  /// `200`: `oklch(93.8% 0.127 124.321deg)`
  ///
  /// `300`: `oklch(89.7% 0.196 126.665deg)`
  ///
  /// `400`: `oklch(84.1% 0.238 128.85deg)`
  ///
  /// `500`: `oklch(76.8% 0.233 130.85deg)`
  ///
  /// `600`: `oklch(64.8% 0.2 131.684deg)`
  ///
  /// `700`: `oklch(53.2% 0.157 131.589deg)`
  ///
  /// `800`: `oklch(45.3% 0.124 130.933deg)`
  ///
  /// `900`: `oklch(40.5% 0.101 131.063deg)`
  ///
  /// `950`: `oklch(27.4% 0.072 132.109deg)`
  static const ColorSwatch<int> lime = ColorSwatch(0xff84cc16, {
    50: Color(0xfff7fee7),
    100: Color(0xffecfccb),
    200: Color(0xffd9f99d),
    300: Color(0xffbef264),
    400: Color(0xffa3e635),
    500: Color(0xff84cc16),
    600: Color(0xff65a30d),
    700: Color(0xff4d7c0f),
    800: Color(0xff3f6212),
    900: Color(0xff365314),
    950: Color(0xff1a2e05),
  });

  /// Corresponds to `--color-green-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.2% 0.018 155.826deg)`
  ///
  /// `100`: `oklch(96.2% 0.044 156.743deg)`
  ///
  /// `200`: `oklch(92.5% 0.084 155.995deg)`
  ///
  /// `300`: `oklch(87.1% 0.15 154.449deg)`
  ///
  /// `400`: `oklch(79.2% 0.209 151.711deg)`
  ///
  /// `500`: `oklch(72.3% 0.219 149.579deg)`
  ///
  /// `600`: `oklch(62.7% 0.194 149.214deg)`
  ///
  /// `700`: `oklch(52.7% 0.154 150.069deg)`
  ///
  /// `800`: `oklch(44.8% 0.119 151.328deg)`
  ///
  /// `900`: `oklch(39.3% 0.095 152.535deg)`
  ///
  /// `950`: `oklch(26.6% 0.065 152.934deg)`
  static const ColorSwatch<int> green = ColorSwatch(0xff22c55e, {
    50: Color(0xfff0fdf4),
    100: Color(0xffdcfce7),
    200: Color(0xffbbf7d0),
    300: Color(0xff86efac),
    400: Color(0xff4ade80),
    500: Color(0xff22c55e),
    600: Color(0xff16a34a),
    700: Color(0xff15803d),
    800: Color(0xff166534),
    900: Color(0xff14532d),
    950: Color(0xff052e16),
  });

  /// Corresponds to `--color-emerald-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(97.9% 0.021 166.113deg)`
  ///
  /// `100`: `oklch(95% 0.052 163.051deg)`
  ///
  /// `200`: `oklch(90.5% 0.093 164.15deg)`
  ///
  /// `300`: `oklch(84.5% 0.143 164.978deg)`
  ///
  /// `400`: `oklch(76.5% 0.177 163.223deg)`
  ///
  /// `500`: `oklch(69.6% 0.17 162.48deg)`
  ///
  /// `600`: `oklch(59.6% 0.145 163.225deg)`
  ///
  /// `700`: `oklch(50.8% 0.118 165.612deg)`
  ///
  /// `800`: `oklch(43.2% 0.095 166.913deg)`
  ///
  /// `900`: `oklch(37.8% 0.077 168.94deg)`
  ///
  /// `950`: `oklch(26.2% 0.051 172.552deg)`
  static const ColorSwatch<int> emerald = ColorSwatch(0xff10b981, {
    50: Color(0xffecfdf5),
    100: Color(0xffd1fae5),
    200: Color(0xffa7f3d0),
    300: Color(0xff6ee7b7),
    400: Color(0xff34d399),
    500: Color(0xff10b981),
    600: Color(0xff059669),
    700: Color(0xff047857),
    800: Color(0xff065f46),
    900: Color(0xff064e3b),
    950: Color(0xff022c22),
  });

  /// Corresponds to `--color-teal-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.4% 0.014 180.72deg)`
  ///
  /// `100`: `oklch(95.3% 0.051 180.801deg)`
  ///
  /// `200`: `oklch(91% 0.096 180.426deg)`
  ///
  /// `300`: `oklch(85.5% 0.138 181.071deg)`
  ///
  /// `400`: `oklch(77.7% 0.152 181.912deg)`
  ///
  /// `500`: `oklch(70.4% 0.14 182.503deg)`
  ///
  /// `600`: `oklch(60% 0.118 184.704deg)`
  ///
  /// `700`: `oklch(51.1% 0.096 186.391deg)`
  ///
  /// `800`: `oklch(43.7% 0.078 188.216deg)`
  ///
  /// `900`: `oklch(38.6% 0.063 188.416deg)`
  ///
  /// `950`: `oklch(27.7% 0.046 192.524deg)`
  static const ColorSwatch<int> teal = ColorSwatch(0xff14b8a6, {
    50: Color(0xfff0fdfa),
    100: Color(0xffccfbf1),
    200: Color(0xff99f6e4),
    300: Color(0xff5eead4),
    400: Color(0xff2dd4bf),
    500: Color(0xff14b8a6),
    600: Color(0xff0d9488),
    700: Color(0xff0f766e),
    800: Color(0xff115e59),
    900: Color(0xff134e4a),
    950: Color(0xff042f2e),
  });

  /// Corresponds to `--color-cyan-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.4% 0.019 200.873deg)`
  ///
  /// `100`: `oklch(95.6% 0.045 203.388deg)`
  ///
  /// `200`: `oklch(91.7% 0.08 205.041deg)`
  ///
  /// `300`: `oklch(86.5% 0.127 207.078deg)`
  ///
  /// `400`: `oklch(78.9% 0.154 211.53deg)`
  ///
  /// `500`: `oklch(71.5% 0.143 215.221deg)`
  ///
  /// `600`: `oklch(60.9% 0.126 221.723deg)`
  ///
  /// `700`: `oklch(52% 0.105 223.128deg)`
  ///
  /// `800`: `oklch(45% 0.085 224.283deg)`
  ///
  /// `900`: `oklch(39.8% 0.07 227.392deg)`
  ///
  /// `950`: `oklch(30.2% 0.056 229.695deg)`
  static const ColorSwatch<int> cyan = ColorSwatch(0xff06b6d4, {
    50: Color(0xffecfeff),
    100: Color(0xffcffafe),
    200: Color(0xffa5f3fc),
    300: Color(0xff67e8f9),
    400: Color(0xff22d3ee),
    500: Color(0xff06b6d4),
    600: Color(0xff0891b2),
    700: Color(0xff0e7490),
    800: Color(0xff155e75),
    900: Color(0xff164e63),
    950: Color(0xff083344),
  });

  /// Corresponds to `--color-sky-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(97.7% 0.013 236.62deg)`
  ///
  /// `100`: `oklch(95.1% 0.026 236.824deg)`
  ///
  /// `200`: `oklch(90.1% 0.058 230.902deg)`
  ///
  /// `300`: `oklch(82.8% 0.111 230.318deg)`
  ///
  /// `400`: `oklch(74.6% 0.16 232.661deg)`
  ///
  /// `500`: `oklch(68.5% 0.169 237.323deg)`
  ///
  /// `600`: `oklch(58.8% 0.158 241.966deg)`
  ///
  /// `700`: `oklch(50% 0.134 242.749deg)`
  ///
  /// `800`: `oklch(44.3% 0.11 240.79deg)`
  ///
  /// `900`: `oklch(39.1% 0.09 240.876deg)`
  ///
  /// `950`: `oklch(29.3% 0.066 243.157deg)`
  static const ColorSwatch<int> sky = ColorSwatch(0xff0ea5e9, {
    50: Color(0xfff0f9ff),
    100: Color(0xffe0f2fe),
    200: Color(0xffbae6fd),
    300: Color(0xff7dd3fc),
    400: Color(0xff38bdf8),
    500: Color(0xff0ea5e9),
    600: Color(0xff0284c7),
    700: Color(0xff0369a1),
    800: Color(0xff075985),
    900: Color(0xff0c4a6e),
    950: Color(0xff082f49),
  });

  /// Corresponds to `--color-blue-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(97% 0.014 254.604deg)`
  ///
  /// `100`: `oklch(93.2% 0.032 255.585deg)`
  ///
  /// `200`: `oklch(88.2% 0.059 254.128deg)`
  ///
  /// `300`: `oklch(80.9% 0.105 251.813deg)`
  ///
  /// `400`: `oklch(70.7% 0.165 254.624deg)`
  ///
  /// `500`: `oklch(62.3% 0.214 259.815deg)`
  ///
  /// `600`: `oklch(54.6% 0.245 262.881deg)`
  ///
  /// `700`: `oklch(48.8% 0.243 264.376deg)`
  ///
  /// `800`: `oklch(42.4% 0.199 265.638deg)`
  ///
  /// `900`: `oklch(37.9% 0.146 265.522deg)`
  ///
  /// `950`: `oklch(28.2% 0.091 267.935deg)`
  static const ColorSwatch<int> blue = ColorSwatch(0xff3b82f6, {
    50: Color(0xffeff6ff),
    100: Color(0xffdbeafe),
    200: Color(0xffbfdbfe),
    300: Color(0xff93c5fd),
    400: Color(0xff60a5fa),
    500: Color(0xff3b82f6),
    600: Color(0xff2563eb),
    700: Color(0xff1d4ed8),
    800: Color(0xff1e40af),
    900: Color(0xff1e3a8a),
    950: Color(0xff172554),
  });

  /// Corresponds to `--color-indigo-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(96.2% 0.018 272.314deg)`
  ///
  /// `100`: `oklch(93% 0.034 272.788deg)`
  ///
  /// `200`: `oklch(87% 0.065 274.039deg)`
  ///
  /// `300`: `oklch(78.5% 0.115 274.713deg)`
  ///
  /// `400`: `oklch(67.3% 0.182 276.935deg)`
  ///
  /// `500`: `oklch(58.5% 0.233 277.117deg)`
  ///
  /// `600`: `oklch(51.1% 0.262 276.966deg)`
  ///
  /// `700`: `oklch(45.7% 0.24 277.023deg)`
  ///
  /// `800`: `oklch(39.8% 0.195 277.366deg)`
  ///
  /// `900`: `oklch(35.9% 0.144 278.697deg)`
  ///
  /// `950`: `oklch(25.7% 0.09 281.288deg)`
  static const ColorSwatch<int> indigo = ColorSwatch(0xff6366f1, {
    50: Color(0xffeef2ff),
    100: Color(0xffe0e7ff),
    200: Color(0xffc7d2fe),
    300: Color(0xffa5b4fc),
    400: Color(0xff818cf8),
    500: Color(0xff6366f1),
    600: Color(0xff4f46e5),
    700: Color(0xff4338ca),
    800: Color(0xff3730a3),
    900: Color(0xff312e81),
    950: Color(0xff1e1b4b),
  });

  /// Corresponds to `--color-violet-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(96.9% 0.016 293.756deg)`
  ///
  /// `100`: `oklch(94.3% 0.029 294.588deg)`
  ///
  /// `200`: `oklch(89.4% 0.057 293.283deg)`
  ///
  /// `300`: `oklch(81.1% 0.111 293.571deg)`
  ///
  /// `400`: `oklch(70.2% 0.183 293.541deg)`
  ///
  /// `500`: `oklch(60.6% 0.25 292.717deg)`
  ///
  /// `600`: `oklch(54.1% 0.281 293.009deg)`
  ///
  /// `700`: `oklch(49.1% 0.27 292.581deg)`
  ///
  /// `800`: `oklch(43.2% 0.232 292.759deg)`
  ///
  /// `900`: `oklch(38% 0.189 293.745deg)`
  ///
  /// `950`: `oklch(28.3% 0.141 291.089deg)`
  static const ColorSwatch<int> violet = ColorSwatch(0xff8b5cf6, {
    50: Color(0xfff5f3ff),
    100: Color(0xffede9fe),
    200: Color(0xffddd6fe),
    300: Color(0xffc4b5fd),
    400: Color(0xffa78bfa),
    500: Color(0xff8b5cf6),
    600: Color(0xff7c3aed),
    700: Color(0xff6d28d9),
    800: Color(0xff5b21b6),
    900: Color(0xff4c1d95),
    950: Color(0xff2e1065),
  });

  /// Corresponds to `--color-purple-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(97.7% 0.014 308.299deg)`
  ///
  /// `100`: `oklch(94.6% 0.033 307.174deg)`
  ///
  /// `200`: `oklch(90.2% 0.063 306.703deg)`
  ///
  /// `300`: `oklch(82.7% 0.119 306.383deg)`
  ///
  /// `400`: `oklch(71.4% 0.203 305.504deg)`
  ///
  /// `500`: `oklch(62.7% 0.265 303.9deg)`
  ///
  /// `600`: `oklch(55.8% 0.288 302.321deg)`
  ///
  /// `700`: `oklch(49.6% 0.265 301.924deg)`
  ///
  /// `800`: `oklch(43.8% 0.218 303.724deg)`
  ///
  /// `900`: `oklch(38.1% 0.176 304.987deg)`
  ///
  /// `950`: `oklch(29.1% 0.149 302.717deg)`
  static const ColorSwatch<int> purple = ColorSwatch(0xffa855f7, {
    50: Color(0xfffaf5ff),
    100: Color(0xfff3e8ff),
    200: Color(0xffe9d5ff),
    300: Color(0xffd8b4fe),
    400: Color(0xffc084fc),
    500: Color(0xffa855f7),
    600: Color(0xff9333ea),
    700: Color(0xff7e22ce),
    800: Color(0xff6b21a8),
    900: Color(0xff581c87),
    950: Color(0xff3b0764),
  });

  /// Corresponds to `--color-fuchsia-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(97.7% 0.017 320.058deg)`
  ///
  /// `100`: `oklch(95.2% 0.037 318.852deg)`
  ///
  /// `200`: `oklch(90.3% 0.076 319.62deg)`
  ///
  /// `300`: `oklch(83.3% 0.145 321.434deg)`
  ///
  /// `400`: `oklch(74% 0.238 322.16deg)`
  ///
  /// `500`: `oklch(66.7% 0.295 322.15deg)`
  ///
  /// `600`: `oklch(59.1% 0.293 322.896deg)`
  ///
  /// `700`: `oklch(51.8% 0.253 323.949deg)`
  ///
  /// `800`: `oklch(45.2% 0.211 324.591deg)`
  ///
  /// `900`: `oklch(40.1% 0.17 325.612deg)`
  ///
  /// `950`: `oklch(29.3% 0.136 325.661deg)`
  static const ColorSwatch<int> fuchsia = ColorSwatch(0xffd946ef, {
    50: Color(0xfffdf4ff),
    100: Color(0xfffae8ff),
    200: Color(0xfff5d0fe),
    300: Color(0xfff0abfc),
    400: Color(0xffe879f9),
    500: Color(0xffd946ef),
    600: Color(0xffc026d3),
    700: Color(0xffa21caf),
    800: Color(0xff86198f),
    900: Color(0xff701a75),
    950: Color(0xff4a044e),
  });

  /// Corresponds to `--color-pink-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(97.1% 0.014 343.198deg)`
  ///
  /// `100`: `oklch(94.8% 0.028 342.258deg)`
  ///
  /// `200`: `oklch(89.9% 0.061 343.231deg)`
  ///
  /// `300`: `oklch(82.3% 0.12 346.018deg)`
  ///
  /// `400`: `oklch(71.8% 0.202 349.761deg)`
  ///
  /// `500`: `oklch(65.6% 0.241 354.308deg)`
  ///
  /// `600`: `oklch(59.2% 0.249 0.584deg)`
  ///
  /// `700`: `oklch(52.5% 0.223 3.958deg)`
  ///
  /// `800`: `oklch(45.9% 0.187 3.815deg)`
  ///
  /// `900`: `oklch(40.8% 0.153 2.432deg)`
  ///
  /// `950`: `oklch(28.4% 0.109 3.907deg)`
  static const ColorSwatch<int> pink = ColorSwatch(0xffec4899, {
    50: Color(0xfffdf2f8),
    100: Color(0xfffce7f3),
    200: Color(0xfffbcfe8),
    300: Color(0xfff9a8d4),
    400: Color(0xfff472b6),
    500: Color(0xffec4899),
    600: Color(0xffdb2777),
    700: Color(0xffbe185d),
    800: Color(0xff9d174d),
    900: Color(0xff831843),
    950: Color(0xff500724),
  });

  /// Corresponds to `--color-rose-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(96.9% 0.015 12.422deg)`
  ///
  /// `100`: `oklch(94.1% 0.03 12.58deg)`
  ///
  /// `200`: `oklch(89.2% 0.058 10.001deg)`
  ///
  /// `300`: `oklch(81% 0.117 11.638deg)`
  ///
  /// `400`: `oklch(71.2% 0.194 13.428deg)`
  ///
  /// `500`: `oklch(64.5% 0.246 16.439deg)`
  ///
  /// `600`: `oklch(58.6% 0.253 17.585deg)`
  ///
  /// `700`: `oklch(51.4% 0.222 16.935deg)`
  ///
  /// `800`: `oklch(45.5% 0.188 13.697deg)`
  ///
  /// `900`: `oklch(41% 0.159 10.272deg)`
  ///
  /// `950`: `oklch(27.1% 0.105 12.094deg)`
  static const ColorSwatch<int> rose = ColorSwatch(0xfff43f5e, {
    50: Color(0xfffff1f2),
    100: Color(0xffffe4e6),
    200: Color(0xfffecdd3),
    300: Color(0xfffda4af),
    400: Color(0xfffb7185),
    500: Color(0xfff43f5e),
    600: Color(0xffe11d48),
    700: Color(0xffbe123c),
    800: Color(0xff9f1239),
    900: Color(0xff881337),
    950: Color(0xff4c0519),
  });

  /// Corresponds to `--color-slate-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.4% 0.003 247.858deg)`
  ///
  /// `100`: `oklch(96.8% 0.007 247.896deg)`
  ///
  /// `200`: `oklch(92.9% 0.013 255.508deg)`
  ///
  /// `300`: `oklch(86.9% 0.022 252.894deg)`
  ///
  /// `400`: `oklch(70.4% 0.04 256.788deg)`
  ///
  /// `500`: `oklch(55.4% 0.046 257.417deg)`
  ///
  /// `600`: `oklch(44.6% 0.043 257.281deg)`
  ///
  /// `700`: `oklch(37.2% 0.044 257.287deg)`
  ///
  /// `800`: `oklch(27.9% 0.041 260.031deg)`
  ///
  /// `900`: `oklch(20.8% 0.042 265.755deg)`
  ///
  /// `950`: `oklch(12.9% 0.042 264.695deg)`
  static const ColorSwatch<int> slate = ColorSwatch(0xff64748b, {
    50: Color(0xfff8fafc),
    100: Color(0xfff1f5f9),
    200: Color(0xffe2e8f0),
    300: Color(0xffcbd5e1),
    400: Color(0xff94a3b8),
    500: Color(0xff64748b),
    600: Color(0xff475569),
    700: Color(0xff334155),
    800: Color(0xff1e293b),
    900: Color(0xff0f172a),
    950: Color(0xff020617),
  });

  /// Corresponds to `--color-gray-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.5% 0.002 247.839deg)`
  ///
  /// `100`: `oklch(96.7% 0.003 264.542deg)`
  ///
  /// `200`: `oklch(92.8% 0.006 264.531deg)`
  ///
  /// `300`: `oklch(87.2% 0.01 258.338deg)`
  ///
  /// `400`: `oklch(70.7% 0.022 261.325deg)`
  ///
  /// `500`: `oklch(55.1% 0.027 264.364deg)`
  ///
  /// `600`: `oklch(44.6% 0.03 256.802deg)`
  ///
  /// `700`: `oklch(37.3% 0.034 259.733deg)`
  ///
  /// `800`: `oklch(27.8% 0.033 256.848deg)`
  ///
  /// `900`: `oklch(21% 0.034 264.665deg)`
  ///
  /// `950`: `oklch(13% 0.028 261.692deg)`
  static const ColorSwatch<int> gray = ColorSwatch(0xff6b7280, {
    50: Color(0xfff9fafb),
    100: Color(0xfff3f4f6),
    200: Color(0xffe5e7eb),
    300: Color(0xffd1d5db),
    400: Color(0xff9ca3af),
    500: Color(0xff6b7280),
    600: Color(0xff4b5563),
    700: Color(0xff374151),
    800: Color(0xff1f2937),
    900: Color(0xff111827),
    950: Color(0xff030712),
  });

  /// Corresponds to `--color-zinc-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.5% 0 0deg)`
  ///
  /// `100`: `oklch(96.7% 0.001 286.375deg)`
  ///
  /// `200`: `oklch(92% 0.004 286.32deg)`
  ///
  /// `300`: `oklch(87.1% 0.006 286.286deg)`
  ///
  /// `400`: `oklch(70.5% 0.015 286.067deg)`
  ///
  /// `500`: `oklch(55.2% 0.016 285.938deg)`
  ///
  /// `600`: `oklch(44.2% 0.017 285.786deg)`
  ///
  /// `700`: `oklch(37% 0.013 285.805deg)`
  ///
  /// `800`: `oklch(27.4% 0.006 286.033deg)`
  ///
  /// `900`: `oklch(21% 0.006 285.885deg)`
  ///
  /// `950`: `oklch(14.1% 0.005 285.823deg)`
  static const ColorSwatch<int> zinc = ColorSwatch(0xff71717a, {
    50: Color(0xfffafafa),
    100: Color(0xfff4f4f5),
    200: Color(0xffe4e4e7),
    300: Color(0xffd4d4d8),
    400: Color(0xffa1a1aa),
    500: Color(0xff71717a),
    600: Color(0xff52525b),
    700: Color(0xff3f3f46),
    800: Color(0xff27272a),
    900: Color(0xff18181b),
    950: Color(0xff09090b),
  });

  /// Corresponds to `--color-neutral-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.5% 0 0deg)`
  ///
  /// `100`: `oklch(97% 0 0deg)`
  ///
  /// `200`: `oklch(92.2% 0 0deg)`
  ///
  /// `300`: `oklch(87% 0 0deg)`
  ///
  /// `400`: `oklch(70.8% 0 0deg)`
  ///
  /// `500`: `oklch(55.6% 0 0deg)`
  ///
  /// `600`: `oklch(43.9% 0 0deg)`
  ///
  /// `700`: `oklch(37.1% 0 0deg)`
  ///
  /// `800`: `oklch(26.9% 0 0deg)`
  ///
  /// `900`: `oklch(20.5% 0 0deg)`
  ///
  /// `950`: `oklch(14.5% 0 0deg)`
  static const ColorSwatch<int> neutral = ColorSwatch(0xff737373, {
    50: Color(0xfffafafa),
    100: Color(0xfff5f5f5),
    200: Color(0xffe5e5e5),
    300: Color(0xffd4d4d4),
    400: Color(0xffa3a3a3),
    500: Color(0xff737373),
    600: Color(0xff525252),
    700: Color(0xff404040),
    800: Color(0xff262626),
    900: Color(0xff171717),
    950: Color(0xff0a0a0a),
  });

  /// Corresponds to `--color-stone-*`
  ///
  /// Original colors:
  ///
  /// `50`: `oklch(98.5% 0.001 106.423deg)`
  ///
  /// `100`: `oklch(97% 0.001 106.424deg)`
  ///
  /// `200`: `oklch(92.3% 0.003 48.717deg)`
  ///
  /// `300`: `oklch(86.9% 0.005 56.366deg)`
  ///
  /// `400`: `oklch(70.9% 0.01 56.259deg)`
  ///
  /// `500`: `oklch(55.3% 0.013 58.071deg)`
  ///
  /// `600`: `oklch(44.4% 0.011 73.639deg)`
  ///
  /// `700`: `oklch(37.4% 0.01 67.558deg)`
  ///
  /// `800`: `oklch(26.8% 0.007 34.298deg)`
  ///
  /// `900`: `oklch(21.6% 0.006 56.043deg)`
  ///
  /// `950`: `oklch(14.7% 0.004 49.25deg)`
  static const ColorSwatch<int> stone = ColorSwatch(0xff78716c, {
    50: Color(0xfffafaf9),
    100: Color(0xfff5f5f4),
    200: Color(0xffe7e5e4),
    300: Color(0xffd6d3d1),
    400: Color(0xffa8a29e),
    500: Color(0xff78716c),
    600: Color(0xff57534e),
    700: Color(0xff44403c),
    800: Color(0xff292524),
    900: Color(0xff1c1917),
    950: Color(0xff0c0a09),
  });

  static const Map<String, ColorSwatch<int>> colorList = {
    'red': red,
    'orange': orange,
    'amber': amber,
    'yellow': yellow,
    'lime': lime,
    'green': green,
    'emerald': emerald,
    'teal': teal,
    'cyan': cyan,
    'sky': sky,
    'blue': blue,
    'indigo': indigo,
    'violet': violet,
    'purple': purple,
    'fuchsia': fuchsia,
    'pink': pink,
    'rose': rose,
    'slate': slate,
    'gray': gray,
    'zinc': zinc,
    'neutral': neutral,
    'stone': stone,
  };
}
