// Generated by `helpers/bin/parse_blur.dart

import 'dart:ui';

/// All blurs defined in Tailwind CSS
abstract class TwBlur {
  /// Equivalent to `blur-xs`
  static final ImageFilter xs = ImageFilter.blur(sigmaX: 4, sigmaY: 4);

  /// Equivalent to `blur-sm`
  static final ImageFilter sm = ImageFilter.blur(sigmaX: 8, sigmaY: 8);

  /// Equivalent to `blur-md`
  static final ImageFilter md = ImageFilter.blur(sigmaX: 12, sigmaY: 12);

  /// Equivalent to `blur-lg`
  static final ImageFilter lg = ImageFilter.blur(sigmaX: 16, sigmaY: 16);

  /// Equivalent to `blur-xl`
  static final ImageFilter xl = ImageFilter.blur(sigmaX: 24, sigmaY: 24);

  /// Equivalent to `blur-xl2`
  static final ImageFilter xl2 = ImageFilter.blur(sigmaX: 40, sigmaY: 40);

  /// Equivalent to `blur-xl3`
  static final ImageFilter xl3 = ImageFilter.blur(sigmaX: 64, sigmaY: 64);
}
